services:
  mongo:
    image: mongo:latest
    container_name: nobito-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - nobito-system

  redis:
    image: redis:7
    container_name: nobito-redis
    restart: always
    ports:
      - '6379:6379'

    networks:
      - nobito-system

volumes:
  rabbitmq_data:
  mysql_data:

networks:
  nobito-system:
    driver: bridge
